[main]
#include = ~/.config/foot/catppuccin-mocha.ini
include = ~/.config/foot/catppuccin-frappe.ini
#initial-window-size-chars=100x35
# Nome da fonte e tamanho
#font=GeistMono NFM:size=12
font=LigaSauceCodePro Nerd Font:size=12
#font=Liga SFMono Nerd Font:size=12

# Opcional: Configurações de DPI e renderização para maior nitidez
dpi-aware=no
# yes senão estiver no VMware

#font-bold=GeistMono NFM:weight=bold:size=12
#font-italic=GeistMono NFM:slant=italic:size=12

